# Generated by Django 5.2.17 on 2026-10-03 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('fitness', 'Fitness'), ('learning', 'Learning'), ('productivity', 'Productivity'), ('finance', 'Finance'), ('social', 'Social'), ('mindfulness', 'Mindfulness'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(default='#4f46e5', max_length=7)),
                ('icon', models.CharField(default='check-circle', max_length=40)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('weekdays', 'Specific weekdays'), ('times_per_week', 'N times per week')], default='daily', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text="0=Mon..6=Sun, used with 'weekdays'")),
                ('target_count', models.PositiveSmallIntegerField(default=1, help_text='Times per week (times_per_week)')),
                ('target_value', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
