# Generated by Django 5.2.17 on 2026-10-03 07:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['habit', '-date'], name='tracking_ha_habit_i_2ce31c_idx')],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='unique_completion_per_day')],
            },
        ),
    ]
