up:
	docker compose up --build
down:
	docker compose down
migrate:
	python manage.py migrate
test:
	pytest
lint:
	ruff check .
format:
	ruff format .
createsuperuser:
	python manage.py createsuperuser
